export const RESET = "WEAPON_UPDATE_RESET";
export const SET_ERROR = "WEAPON_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "WEAPON_UPDATE_SET_RETRIEVED";
export const SET_UPDATED = "WEAPON_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "WEAPON_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "WEAPON_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "WEAPON_UPDATE_UPDATE_RETRIEVED";
