export const ARTIFACT_CREATE_RESET = "ARTIFACT_CREATE_RESET";
export const ARTIFACT_CREATE_SET_CREATED = "ARTIFACT_CREATE_SET_CREATED";
export const ARTIFACT_CREATE_SET_ERROR = "ARTIFACT_CREATE_SET_ERROR";
export const ARTIFACT_CREATE_SET_VIOLATIONS = "ARTIFACT_CREATE_SET_VIOLATIONS";
export const ARTIFACT_CREATE_TOGGLE_LOADING = "ARTIFACT_CREATE_TOGGLE_LOADING";
