export const RESET = "BUFF_UPDATE_RESET";
export const SET_ERROR = "BUFF_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "BUFF_UPDATE_SET_RETRIEVED";
export const SET_UPDATED = "BUFF_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "BUFF_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "BUFF_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "BUFF_UPDATE_UPDATE_RETRIEVED";
