export const PATCHCHAR_CREATE_RESET = "PATCHCHAR_CREATE_RESET";
export const PATCHCHAR_CREATE_SET_CREATED = "PATCHCHAR_CREATE_SET_CREATED";
export const PATCHCHAR_CREATE_SET_ERROR = "PATCHCHAR_CREATE_SET_ERROR";
export const PATCHCHAR_CREATE_SET_VIOLATIONS =
  "PATCHCHAR_CREATE_SET_VIOLATIONS";
export const PATCHCHAR_CREATE_TOGGLE_LOADING =
  "PATCHCHAR_CREATE_TOGGLE_LOADING";
