export const PATCHCHAR_DELETE_RESET = "PATCHCHAR_DELETE_RESET";
export const PATCHCHAR_DELETE_SET_ERROR = "PATCHCHAR_DELETE_SET_ERROR";
export const PATCHCHAR_DELETE_SET_DELETED = "PATCHCHAR_DELETE_SET_DELETED";
export const PATCHCHAR_DELETE_TOGGLE_LOADING =
  "PATCHCHAR_DELETE_TOGGLE_LOADING";
