export const WEAPON_SHOW_RESET = "WEAPON_SHOW_RESET";
export const WEAPON_SHOW_SET_ERROR = "WEAPON_SHOW_SET_ERROR";
export const WEAPON_SHOW_SET_RETRIEVED = "WEAPON_SHOW_SET_RETRIEVED";
export const WEAPON_SHOW_TOGGLE_LOADING = "WEAPON_SHOW_TOGGLE_LOADING";
