export const RESET = "CHARACTER_UPDATE_RESET";
export const SET_ERROR = "CHARACTER_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "CHARACTER_UPDATE_SET_RETRIEVED";
export const SET_UPDATED = "CHARACTER_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "CHARACTER_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "CHARACTER_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "CHARACTER_UPDATE_UPDATE_RETRIEVED";
