export const WEAPON_DELETE_RESET = "WEAPON_DELETE_RESET";
export const WEAPON_DELETE_SET_ERROR = "WEAPON_DELETE_SET_ERROR";
export const WEAPON_DELETE_SET_DELETED = "WEAPON_DELETE_SET_DELETED";
export const WEAPON_DELETE_TOGGLE_LOADING = "WEAPON_DELETE_TOGGLE_LOADING";
