export const CHARACTER_CREATE_RESET = "CHARACTER_CREATE_RESET";
export const CHARACTER_CREATE_SET_CREATED = "CHARACTER_CREATE_SET_CREATED";
export const CHARACTER_CREATE_SET_ERROR = "CHARACTER_CREATE_SET_ERROR";
export const CHARACTER_CREATE_SET_VIOLATIONS =
  "CHARACTER_CREATE_SET_VIOLATIONS";
export const CHARACTER_CREATE_TOGGLE_LOADING =
  "CHARACTER_CREATE_TOGGLE_LOADING";
