export const RESET = "PATCHCHAR_UPDATE_RESET";
export const SET_ERROR = "PATCHCHAR_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "PATCHCHAR_UPDATE_SET_RETRIEVED";
export const SET_UPDATED = "PATCHCHAR_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "PATCHCHAR_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "PATCHCHAR_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "PATCHCHAR_UPDATE_UPDATE_RETRIEVED";
