export const RESET = "PATCHCHAR_LIST_RESET";
export const SET_ITEMS = "PATCHCHAR_LIST_SET_ITEMS";
export const SET_ERROR = "PATCHCHAR_LIST_SET_ERROR";
export const SET_SELECT_ITEMS = "PATCHCHAR_LIST_SET_SELECT_ITEMS";
export const SET_VIEW = "PATCHCHAR_LIST_SET_VIEW";
export const TOGGLE_LOADING = "PATCHCHAR_LIST_TOGGLE_LOADING";
