export const RESET = "ARTIFACT_LIST_RESET";
export const SET_ITEMS = "ARTIFACT_LIST_SET_ITEMS";
export const SET_ERROR = "ARTIFACT_LIST_SET_ERROR";
export const SET_SELECT_ITEMS = "ARTIFACT_LIST_SET_SELECT_ITEMS";
export const SET_VIEW = "ARTIFACT_LIST_SET_VIEW";
export const TOGGLE_LOADING = "ARTIFACT_LIST_TOGGLE_LOADING";
