export const WEAPON_CREATE_RESET = "WEAPON_CREATE_RESET";
export const WEAPON_CREATE_SET_CREATED = "WEAPON_CREATE_SET_CREATED";
export const WEAPON_CREATE_SET_ERROR = "WEAPON_CREATE_SET_ERROR";
export const WEAPON_CREATE_SET_VIOLATIONS = "WEAPON_CREATE_SET_VIOLATIONS";
export const WEAPON_CREATE_TOGGLE_LOADING = "WEAPON_CREATE_TOGGLE_LOADING";
