export const ARTIFACT_SHOW_RESET = "ARTIFACT_SHOW_RESET";
export const ARTIFACT_SHOW_SET_ERROR = "ARTIFACT_SHOW_SET_ERROR";
export const ARTIFACT_SHOW_SET_RETRIEVED = "ARTIFACT_SHOW_SET_RETRIEVED";
export const ARTIFACT_SHOW_TOGGLE_LOADING = "ARTIFACT_SHOW_TOGGLE_LOADING";
