export const CHARACTER_DELETE_RESET = "CHARACTER_DELETE_RESET";
export const CHARACTER_DELETE_SET_ERROR = "CHARACTER_DELETE_SET_ERROR";
export const CHARACTER_DELETE_SET_DELETED = "CHARACTER_DELETE_SET_DELETED";
export const CHARACTER_DELETE_TOGGLE_LOADING =
  "CHARACTER_DELETE_TOGGLE_LOADING";
