export const RESET = "ARTIFACT_UPDATE_RESET";
export const SET_ERROR = "ARTIFACT_UPDATE_SET_ERROR";
export const SET_RETRIEVED = "ARTIFACT_UPDATE_SET_RETRIEVED";
export const SET_UPDATED = "ARTIFACT_UPDATE_SET_UPDATED";
export const SET_VIOLATIONS = "ARTIFACT_UPDATE_SET_VIOLATIONS";
export const TOGGLE_LOADING = "ARTIFACT_UPDATE_TOGGLE_LOADING";
export const UPDATE_RETRIEVED = "ARTIFACT_UPDATE_UPDATE_RETRIEVED";
