export const PATCHCHAR_SHOW_RESET = "PATCHCHAR_SHOW_RESET";
export const PATCHCHAR_SHOW_SET_ERROR = "PATCHCHAR_SHOW_SET_ERROR";
export const PATCHCHAR_SHOW_SET_RETRIEVED = "PATCHCHAR_SHOW_SET_RETRIEVED";
export const PATCHCHAR_SHOW_TOGGLE_LOADING = "PATCHCHAR_SHOW_TOGGLE_LOADING";
