export const ARTIFACT_DELETE_RESET = "ARTIFACT_DELETE_RESET";
export const ARTIFACT_DELETE_SET_ERROR = "ARTIFACT_DELETE_SET_ERROR";
export const ARTIFACT_DELETE_SET_DELETED = "ARTIFACT_DELETE_SET_DELETED";
export const ARTIFACT_DELETE_TOGGLE_LOADING = "ARTIFACT_DELETE_TOGGLE_LOADING";
