export const RESET = "WEAPON_LIST_RESET";
export const SET_ITEMS = "WEAPON_LIST_SET_ITEMS";
export const SET_ERROR = "WEAPON_LIST_SET_ERROR";
export const SET_SELECT_ITEMS = "WEAPON_LIST_SET_SELECT_ITEMS";
export const SET_VIEW = "WEAPON_LIST_SET_VIEW";
export const TOGGLE_LOADING = "WEAPON_LIST_TOGGLE_LOADING";
