export const RESET = "CHARACTER_LIST_RESET";
export const SET_ITEMS = "CHARACTER_LIST_SET_ITEMS";
export const SET_ERROR = "CHARACTER_LIST_SET_ERROR";
export const SET_SELECT_ITEMS = "CHARACTER_LIST_SET_SELECT_ITEMS";
export const SET_VIEW = "CHARACTER_LIST_SET_VIEW";
export const TOGGLE_LOADING = "CHARACTER_LIST_TOGGLE_LOADING";
