export const BUFF_SHOW_RESET = "BUFF_SHOW_RESET";
export const BUFF_SHOW_SET_ERROR = "BUFF_SHOW_SET_ERROR";
export const BUFF_SHOW_SET_RETRIEVED = "BUFF_SHOW_SET_RETRIEVED";
export const BUFF_SHOW_TOGGLE_LOADING = "BUFF_SHOW_TOGGLE_LOADING";
