export const BUFF_DELETE_RESET = "BUFF_DELETE_RESET";
export const BUFF_DELETE_SET_ERROR = "BUFF_DELETE_SET_ERROR";
export const BUFF_DELETE_SET_DELETED = "BUFF_DELETE_SET_DELETED";
export const BUFF_DELETE_TOGGLE_LOADING = "BUFF_DELETE_TOGGLE_LOADING";
