export const CHARACTER_SHOW_RESET = "CHARACTER_SHOW_RESET";
export const CHARACTER_SHOW_SET_ERROR = "CHARACTER_SHOW_SET_ERROR";
export const CHARACTER_SHOW_SET_RETRIEVED = "CHARACTER_SHOW_SET_RETRIEVED";
export const CHARACTER_SHOW_TOGGLE_LOADING = "CHARACTER_SHOW_TOGGLE_LOADING";
