export const BUFF_CREATE_RESET = "BUFF_CREATE_RESET";
export const BUFF_CREATE_SET_CREATED = "BUFF_CREATE_SET_CREATED";
export const BUFF_CREATE_SET_ERROR = "BUFF_CREATE_SET_ERROR";
export const BUFF_CREATE_SET_VIOLATIONS = "BUFF_CREATE_SET_VIOLATIONS";
export const BUFF_CREATE_TOGGLE_LOADING = "BUFF_CREATE_TOGGLE_LOADING";
